default: &default
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fetchsamurais_development

test:
  <<: *default
  database: fetchsamurais_test

production:
  <<: *default
  database: fetchsamurais_production
  username: fetchsamurais
  password: <%= ENV["FETCHSAMURAIS_DATABASE_PASSWORD"] %>
